### ISSUE TITLE
在Win10系统下运行的。

### ISSUE THREAD

**Issue by zhangcun-yan** [neozhaoliang/visual-vehicle-behavier-analyzer#2]
> 
> 
> 非常感谢您的帮助，我查到我的原因是opecncv 的版本太高了，当我删除最新的4.4版本重新安装3.4版本之后问题解决了，跑通了，安装代码如下 pip3 install -i https://pypi.doubanio.com/simple/ opencv-contrib-python=3.4.2.16，再次感谢！！

@YANzhangcun 你好，我也遇到了相同的问题，在Windows 10系统下降级了OpenCV到3.4之后还是没有解决，请问你使用的系统也是Linux的吗？

_Originally posted by @hy741oo in https://github.com/neozhaoliang/visual-vehicle-behavier-analyzer/issues/1#issuecomment-728671245_

**Comment by neozhaoliang** [comment]
我大约找到问题原因了，已经修正。应该是 opencv 不同版本对获取视频的时间戳行为不同导致的。
