### ISSUE TITLE
车道检测

### ISSUE THREAD

**Issue by yujia1996** [neozhaoliang/visual-vehicle-behavier-analyzer#3]
您好，请问可以实现车道的检测吗 ？就是输出的csv文件里包括每辆车所在的车道编号 1、2、3、4

**Comment by neozhaoliang** [comment]
这个在项目里面没有实现，但是理论上是可以加入的。只要将车道线的方位坐标在标定时一并采集，并根据车辆的坐标进行比对即可。

另一种方法是使用其它能够检测射车道线的网络进行额外的检测和比对。
