### ISSUE TITLE
如何提升检测准确度？

### ISSUE THREAD

**Issue by hy741oo** [neozhaoliang/visual-vehicle-behavier-analyzer#4]
您好，请问该项目可以通过修改某些参数来达到检测小目标的效果吗？我这里有一个用无人机拍摄的车流视频，但是因为无人机飞行高度太高，车辆的就显得很小，导致检测识别率不高，不知道能不能在当前视频不变动的情况下提升检测准确度。
我根据百度上搜索到的一些解答修改了“yolov3.cfg”文件下的“width”和“height”字段，但是实际检测出来的结果看起来没有变化。

**Comment by hy741oo** [comment]
我自己找到地方了，在Python脚本文件`analyzer/conv_nets.py`第43行的位置，方法`cv2.dnn.blobFromImage`内的第三个参数，更改为以32为倍数的值即可，默认为`(416, 416)`，数值越大检测准确率越好，也越耗费时间，但是准确度并不绝对，也有可能降低了性能，准确度却没有太大提升，在我个人情况下最好的数值为`(704, 704)`。

**Comment by hdmjdp** [comment]
为什么我跑的结果是空的

**Comment by hy741oo** [comment]
@hdmjdp 如果你使用默认的参数运行项目会有结果的话，那可能就是你设置的我提到的参数数值太大了，这个参数数值太大了的话会连原本能识别出来的对象变得识别不出来，需要将该参数设置得小一些。如果你指的是克隆项目，配置相应设置之后直接运行还是没有任何结果的话，那应该和我之前遇到的问题一样，关于这个问题的解决方法我在问题 #1 里面和其他用户探讨了一下，应该可以供你参考，最后我的方法是安装Ubuntu虚拟机然后重新跑一遍就解决了。

**Comment by hdmjdp** [comment]
后者，我直接跑的源代码，运行后，只有车道和世界坐标。没有车辆轨迹，opencv，我也改成了你说的版本

**Comment by hy741oo** [comment]
你是在Windows系统下跑的还是Linux系统下跑的？

**Comment by hdmjdp** [comment]
linux，准确说是mac。我想问下，是要先运行那个calibrate开头的文件吗，再运行main.py？

**Comment by hy741oo** [comment]
`camera_calibration.py`这个文件的作用是在图片和现实场景之间做一个映射，关于使用方法稍微有点复杂，但是作者本身的项目里已经完成了这个映射步骤，因此如果使用的是作者的视频那么就不需要运行这个文件，直接运行`main.py`即可，并且在运行过程中也不需要有任何操作。关于系统的问题，mac电脑的系统我也就不是很了解了，我只在Ubuntu 18.04系统和Windows 10系统下做过测试，我也只有在Ubuntu系统下才能正确运行项目并得到结果。

**Comment by hdmjdp** [comment]
yolo的weight你下的多大，我怀疑可能是我下的这个文件有问题。下了半天才下下来。320M

**Comment by hy741oo** [comment]
现在运行这个项目的电脑不在我的身边，如果你使用的是作者在`README.md`文件里提供的链接下载的weight文件的话那我的和你的是一样的。大小确实是这么大，300m左右。

**Comment by hdmjdp** [comment]
嗯，很奇怪，也没报错，不出检测结果

**Comment by hdmjdp** [comment]
搞好了，下载的文件有问题，另外你有试过mask-rcnn吗，yolo感觉不是很准

**Comment by hy741oo** [comment]
解决了就好。别的算法我就没有试过了，我就只有用过yolo的。

**Comment by hdmjdp** [comment]
图片和现实场景之间做一个映射 这个怎么映射的，就是哪个yaml文件，几个矩阵怎么得出来的

**Comment by hy741oo** [comment]
因为我手头上没有我的项目，所以只能大概给你说明一下。
1. 首先就是截取一张你要做测试的视频的截图，然后在这个截图上选取四个标记点，这四个标记点没有硬性的要求，但是你需要记录下来每一个标记点的图像位置（单位为象素）还有实际位置（单位分别为经度和纬度），以及一个作为坐标原点的标记点（可以用这四个标记点之一），以及一个用于测试映射准确度的测试点的实际位置。当你准备好这些材料之后可以打开（而不是运行）`camera_calibration.py`这个文件，查看对应代码里是如何引用这一张图片以及这些标记点是如何使用的，图片的引用很简单，就只是选择对应的路径即可，标记点的使用可以查看该文件里有一个方法引用到了一个yaml文件，打开这个yaml文件可以看到一些数组，对照着这些每一组数组的字段名和被引用到的图片来看的话很容易发现如何对应上的。
2. 运行Python脚本文件`camera_calibration.py`，第一次会弹出来一个窗口，这个窗口就是步骤1当中被应用到的那张图片，然后会发现这张图片上面会有红色的红点，这些点就是项目映射之后的结果，你需要对照着这些点的位置比对自己找到的标记点的位置是否吻合，以及在这个窗口上的照片里你可以看到一个蓝色的点，这个点就是利用步骤1当中选定的测试点的经纬度位置，通过映射关系映射到图片上的位置，这个点也可以反映出你自己选择的点的图像位置和实际位置之间的差距，该点越和你自己选定的点的位置重合，表明映射关系越正确。如果确定了映射位置正确的话，那就点击`Enter`键来将映射关系写到另一个yaml文件里，然后点击`q`键即可退出。
3. 在步骤2里退出之后，会弹出一个新的窗口，该窗口是用于选定检测区域的，你只需要用鼠标左键在窗口内选择位置，即可标志出需要检测的范围，这个范围是任意的，它会在你选取的所有点上选取出一个闭合的区域，因此你可以不用按照传统的选取矩形位置，或者是只选取四个点。选取好检测范围后，点击`Entrer`键即可将选择好的区域信息保存到另外一个yaml文件里，然后点击`q`键即可退出。
4. 到这一步之后映射关系就已经设置好了，现在你可以打开Python脚本文件`main.py`在代码里引用你需要的视频路径等一些必要的文件，然后运行该文件即可。

**Comment by hdmjdp** [comment]
非常感谢，我研究下

**Comment by hdmjdp** [comment]
我有这样的无人机视频，发现程序第一次显示视频的时候，根本检测不到车辆。
[YOLOV3_screenshot_04.01.2021.png.zip](https://github.com/neozhaoliang/visual-vehicle-behavier-analyzer/files/5761941/YOLOV3_screenshot_04.01.2021.png.zip)

**Comment by hy741oo** [comment]
你可以按照我在当前Issue里解决问题的方法设置一下检测准确度，其实准确来讲我更改的参数应该被叫做“输出图像尺寸”，但是我没有深入研究过这个领域的内容，所以也不是很能准确描述出该参数的作用，但是更改这个参数的值确实能够影响到对象检测的准确度。你可以适当的调大和调小参数，然后再进行测试。
顺便问一下你的问题是在运行自己的视频时候才会出现的吗？还是说运行项目作者的视频时候也会出现？如果是前者的话，那通过我的这个方法应该会有一定的改善，如果是后者的话，那可能和系统或者是一些依赖库的版本有关。

**Comment by hdmjdp** [comment]
@hy741oo 自己视频，我按照你说的方式改成了（704，704），还是无法检测到车辆。可能要自己训练一个yolov3的无人机视频下的车辆模型。你那边无人机视频跟我发的图片情况类似吗

**Comment by hy741oo** [comment]
那问题的原因我也不清楚了，我这边的视频跟你发的图片差不多，不过不是完全从顶视图方向上拍摄的，而是有一定的倾斜角。
