### ISSUE TITLE
没有汽车的检测结果

### ISSUE THREAD

**Issue by hdmjdp** [neozhaoliang/visual-vehicle-behavier-analyzer#5]
你好，只有车道线和坐标， trajectories.csv 是空的

**Comment by neozhaoliang** [comment]
@hdmjdp  问题解决了吗？试试降低 opencv 的版本到 4.0 或者 3.4

**Comment by neozhaoliang** [comment]
我修复了一处可能导致问题的 bug，使用 opencv 4.3 应该可以了。
