### ISSUE TITLE
您好，我运行了项目没有出现trajectory_result.mp4和trajectories.csv文件

### ISSUE THREAD

**Issue by liuaaron-sys** [neozhaoliang/visual-vehicle-behavier-analyzer#6]
下面是报错信息，说是有文件找不到
![image](https://user-images.githubusercontent.com/54876753/108631857-fcd2d200-74a6-11eb-849d-e1ea4ec82500.png)

ffmpeg已经下载了，是不是里面的-i 参数需要加一个文件的路径呢？
![image](https://user-images.githubusercontent.com/54876753/108632068-fee96080-74a7-11eb-9713-2f3dc996ab32.png)

**Comment by liuaaron-sys** [comment]
麻烦您帮我看一下

**Comment by neozhaoliang** [comment]
建议看下之前的 issue。据我了解基本都是 opencv 版本的问题。

**Comment by neozhaoliang** [comment]
和那个 "-i -" 其实没有关系， 那其实是告诉 ffmpge 进程等待输入。你确定你的电脑上安装了 ffmpeg，并且添加到了系统路径了吗？
